### PR TITLE
add ignore option [WIP] Do NOT review

### PR DESCRIPTION
**Pull request by bevhatzl**
Adding a new option "ignore" for no logging.

### CODE REVIEW

**Comment by jamesz96** [comment]
What is an example usage of this logger option?

I'm thinking this can be useful when wanting to temporarily disable a log (rather than commenting it out), but maybe you had something else in mind.

**Comment by bevhatzl** [comment]
There is no need for this option anymore.

**Comment by keithbro** [comment]
The goal here was to be able to disable logging entirely in an environment (useful for the spec env). What conclusion did you come to that you decided to abandon the idea?

**Comment by bevhatzl** [comment]
> 

I think I found that we wouldn't want to disable the logging for any environment, and wouldn't want to encourage disabling it by including this ignore option.

**Pull request closed without merging**
